services:
 - type: cron
   name: cronometer
   env: python
   schedule: "0 5 * * *"
   buildCommand: pip install -r requirements.txt
   startCommand: python main.py
   envVars:
    - fromGroup: My Group
