services:
 - type: cron
   name: cronometer
   env: python
   schedule: "0 4 * * *"
   buildCommand: pip install -r requirements.txt
   startCommand: python main.py
   envVars:
    - fromGroup: My Group
    - key: STRIPE_API_KEY
        value: Z2V0IG91dHRhIGhlcmUhCg
